#!/usr/bin/env bash
# ==============================================================================
# Script Name:    gl_xcelium
# Description:    Helper script: gate-level simulation with xcelium
# Author:         David Trevisan
# Copyright:      (c) 2025 DT
# License:        MIT
# ==============================================================================
# Usage:          --
# Dependencies:   xcelium, synthesis files
# ==============================================================================

set -euo pipefail

scriptFull=$(readlink -f "$0")
scriptPath=$(dirname "${scriptFull}")
rootPath=$(realpath $(dirname "${scriptPath}"))

mkdir -p "${rootPath}/simul.gate"
pushd "${rootPath}/simul.gate"
pwd

# work + vital libraries and lib/var files
mkdir -p vital work
# specific paths to eda-27267 server
# cds.lib
cat > cds.lib <<EOF
INCLUDE /opt/cadence/installs/XCELIUM2009/tools.lnx86/inca/files/cdsvhdl.lib
DEFINE VITAL ./vital
DEFINE WORK ./work
EOF
# hdl.var
cat > hdl.var <<EOF
INCLUDE /opt/cadence/installs/XCELIUM2009/tools.lnx86/inca/files/hdl.var
EOF

# Manually include all files for gate-level
xmvlog -work VITAL ../synth/libs/stdcells.v
# xmvhdl -v93 -work VITAL ../synth/libs/vital/stdcells_Vcomponents.vhdl
# xmvhdl -v93 -work VITAL ../synth/libs/vital/stdcells_Vtables.vhdl
# xmvhdl -v93 -work VITAL ../synth/libs/vital/stdcells_VITAL.vhdl
xmvlog -work WORK ../synth/output/device.syn_opt.v
xmvhdl -v93 -work WORK device_wrapper.vhdl
xmvhdl -v93 -work WORK device_pkg_NBITS32.vhdl # GL Modified to match synthesis
xmvhdl -v93 -work WORK ../code/lfsr_pkg.vhdl
xmvhdl -v93 -work WORK ../code/tester_pkg.vhdl
xmvhdl -v93 -work WORK ../code/tester.vhdl
xmvhdl -v93 -work WORK testbench.vhdl # GL Modified to match synthesis

xmelab -generic "NBITS => 32" -generic "NTESTS => 100" -access +rwc testbench
xmsim -input ../scripts/gl_xmsim.tcl testbench

popd