= Other Device: Maximum Common Divisor (MCD)

Questa sezione analizza il dispositivo `MCD` come quarto componente nello studio del _design flow_ dei dispositivi e calcolatori elettronici.
Verranno analizzati il codice originale per spiegarne il funzionamento e fornire una rappresentazione grafica della sua Control Unit e Datapath.

Verranno poi spiegate le informazioni salienti sullo sviluppo dell'algoritmo di test e del testbench per valutare e verificare il dispositivo `MCD` a livello _RT_ e _gate-level_.

Si concluderá infine il capitolo con valutazioni sulla sintesi del device ed i risultati ottenuti con la libreria tecnologica scelta.

== Code analysis

Il dispositivo é progettato per calcolare il _massimo comun divisore_ tra due numeri (operandi) forniti in ingresso.

Si ricorda che:
> il massimo comun divisore di due numeri interi, entrambi non nulli, corrisponde al numero naturale più grande per il quale entrambi possono essere divisi esattamente.

Dall'anilisi delle porte di _top-level_ del componente `mcd`, si ottiene il seguente prospetto:


[table_mcd_IOports,subs="attributes+"]
[cols="^2m,^2,6",options="header"]
|===

|Signal
|Direction
|Description

|abort
|IN
|

|operand1
|IN
|Primo operando per la ricerca del MCD

|operand2
|IN
|Secondo operando per la ricerca del MCD

|res
|OUT
|Risultato dell'elaborazione, MCD di `operand1` e `operand2`

|start
|IN
|Segnale di `valid` per gli operandi in ingresso.
Richiede una nuova computazione del MCD.

|ready
|OUT
|Segnale di `valid` di `res`.
Indica che il risultato in uscita al dispositivo puó essere valutato.

|===

[.center,svgbob-mcd_ports]
[svgbob]
----
                           +----------------+
   operand1[OPSIZE] ------>|                |
   operand2[OPSIZE] ------>|                |----> res [OPSIZE]
                           |                |
                           |      mcd       |
              start ------>|                |----> ready
              abort ------>|                |
                           |                |
                           +----------------+
----

Il file `mcd.vhdl` contiene una rappresentazione strutturale del dispositivo, istanziando semplicemente control unit e datapath, insieme alla logica di collegamento interna ed alle porte.
Il dispositivo presenta un parametro `generic OPSIZE` di tipo intero, utilizzato per definire la larghezza in bit degli operandi e del risultato.

Il file `mcd_ctrl.vhdl` rappresenta la control unit del dispositivo in maniera comportamentale, implementando una semplice FSM (`ns_process`) per gestire le operazioni ed i segnali di controllo.
Lo stile utilizzato esplicita i segnali di load dei registri presenti nel datapath, ed i selettori dei multiplexer utilizzati attraverso statement concorrenti in maniera coerente con i dispositivi fin'ora analizzati.

Il file `mcd_dp.vhdl` implementa quindi il datapath in maniera gerarchica, istanziando il dispositivo `divider` al suo interno.


=== ASM Chart
== Tester and Testbench development
== Simulations, Synthesis and Evaluations
=== RTL Simulations
=== Stdcells synthesis
=== Gate-level Simulations
=== Other evaluations
